apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-tiya
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-tiya
    app.kubernetes.io/part-of: ci1t-830-0041-app
  name: devfile-sample-tiya
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-tiya
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-tiya
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0041-tenant/ci1t-830-0041-app/devfile-sample-tiya@sha256:5312e9541e75841608637d148079c809b292b2eb886e3b536bc98ac3f24e8629
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
